# -*- coding: utf-8 -*-
"""Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14pgyB647kfuqkOYD-Jkl8lKpvMBuPlAh

**TALLER 1**
"""

no_ident = input("No identificación: ")
Nom = input("Nombres: ")
Ap = input("Apellidos:")
Direc = input("Dirección de residencia: ")
Tel = input("Telefono de contacto: ")
Edad = input("Edad (años): ")
EC = input("Estado civil: ")
NoH = input("¿Cuántos hijos tiene?:")
Estatura = input("Estatura (cm): ")
F_contrato = input("Fecha de ingreso al trabajo actual (dd/mm/aaaa): ")
Salario = input("Sueldo básico (COP): ")
Dias_lab = input("Cantidad de días laborados:")
print(no_ident,
      Nom,
      Ap,
      Direc,
      Tel,
      Edad,
      EC,
      NoH,
      Estatura,
      F_contrato,
      Salario,
      Dias_lab)

no_ident = input("No identificación: ")
Nom = input("Nombres: ")
Ap = input("Apellidos:")
Direc = input("Dirección de residencia: ")
Tel = input("Telefono de contacto: ")
Edad = input("Edad (años): ")
EC = input("Estado civil: ")
NoH = input ("¿Cuántos hijos tiene?:")
Estatura = input("Estatura (cm): ")
F_contrato = input("Fecha de ingreso al trabajo actual (dd/mm/aaaa): ")
Salario = input("Sueldo básico (COP): ")
Dias_lab = input("Cantidad de días laborados:")
print(no_ident, Nom, Ap, Direc, Tel, Edad, EC, NoH, Estatura, F_contrato, Salario, Dias_lab, "Gracias")

"""**EJERCICIOS PRÁCTICOS**

1. Un vendedor recibe un sueldo base más un 10% extra por
comisión de sus ventas, el vendedor desea saber cuánto
dinero obtendrá por concepto de comisiones por las tres
ventas que realiza en el mes y el total que recibirá en
el mes tomando en cuenta su sueldo base y comisiones.
"""

paid = int(input("Ingrese su sueldo base: "))
sale1 = int(input("\nIngrese el valor de la venta 1: "))
sale2 = int(input("Ingrese el valor de la venta 2: "))
sale3 = int(input("Ingrese el valor de la venta 3: "))
com_sale = (sale1 + sale2 + sale3) * 0.10
total_paid = (paid + com_sale)
print(f"\nSus comisiones para el mes en relación son de ${com_sale}, para un pago total ${total_paid} ")

"""2. Una tienda ofrece un descuento del 15% sobre el total
de la compra y un cliente desea saber cuánto deberá
pagar finalmente por su compra.
"""

buy = int(input("Ingrese valor de la compra:  "))
descuento = buy * 0.15
total = buy - descuento
print("\nEl descuento de su compra es ${:,.2f}, para un total de ${:,.2f}".format(descuento, total))

"""3. Un alumno desea saber cuál será su calificación final en
la materia de Algoritmos. Dicha calificación se compone
de tres exámenes parciales.
"""

note1 = float(input("Ingrese nota del primer parcial: "))
note2 = float(input("Ingrese nota del segundo parcial: "))
note3 = float(input("Ingrese nota del tercer parcial: "))
final = (note1 + note2 + note3)/3
print(f"\nSu nota final es {final}")

"""4. Un maestro desea saber qué porcentaje de hombres y que
porcentaje de mujeres hay en un grupo de estudiantes.
"""

tot = int(input("Ingrese total de estudiante: "))
fem = int(input("Ingrese total de mujeres: "))
hom = int(input("Ingrese total de hombres: "))
pp_fem = round(100/tot*fem, 2)
pp_hom = round(100/tot*hom, 2)
print(f"\nEl porcentaje de estudiantes mujeres es de {pp_fem}% y el de hombre es de {pp_hom}%")

"""**TALLER 2**

Dando continuidad con la primera entrega del proyecto, en esta oportunidad el estudiante debe realizar las siguientes validaciones utilizando la sentencia condicional IF.

1. Si el empleado es mayor de 55 años disfrutará de un bono de prepensión correspondiente al 5% de su sueldo básico.

2. Si el empleado es casado y tiene hijos se le otorgará un paseo cada diciembre

3. Si el sueldo básico está entre 1000000 y 1500000 tendrá una comisión del 2% sobre el valor del sueldo; Si el sueldo básico está entre 1500001 y 2000000 tendrá una comisión del 5% sobre el valor del sueldo; para todos los demás casos no habrá comisión.

4. Si el empleado trabajó más de 20 días al mes y su sueldo es menor a 1000000 tendrá derecho a un bono de alimentación
"""

no_ident = input("No identificación: ")
nom = input("Nombres: ")
ap = input("Apellidos:")
direc = input("Dirección de residencia: ")
tel = input("Telefono de contacto: ")
edad = int(input("Edad (años): "))
ec = input("Estado civil: ")
noh = int(input("¿Cuántos hijos tiene?:"))
estatura = input("Estatura (cm): ")
f_contrato = input("Fecha de ingreso al trabajo actual (dd/mm/aaaa): ")
salario = float(input("Sueldo básico (COP): "))
dias_lab = int(input("Cantidad de días laborados al mes:"))

if edad > 55:
  bonop = round(salario * 0.05, 0)
  print(f"\nCuenta con bono de prepensión igual a ${bonop}")
else:
  print(f"\nNo cumple con los requisitos para adquirir bono de prepensión")
if ec in "casado" and noh != 0:
  fam = "\nPaseo decembrino"
else:
  print("\nNo cumple con los requisitos para acceder al paseo decembrino")
if salario >= 1000000 and salario <= 1500000:
  com1 = round(salario * 0.02, 0)
  print(f"\nRecibirá comisión de ${com1}")
elif salario >= 1500001 and salario <= 2000000:
  com2 = round(salario *0.05, 0)
  print(f"\nRecibirá comisión de ${com2}")
else:
  print("\nNo cuenta con los requisistos para obtener comisión")
if dias_lab > 20 and salario < 1000000:
  bonoa = "\nDerecho a bono de alimentación"
else:
  print("\nNo aplica para el bono de alimentación")

no_ident = input("No identificación: ")
nom = input("Nombres: ")
ap = input("Apellidos:")
direc = input("Dirección de residencia: ")
tel = input("Telefono de contacto: ")
edad = int(input("Edad (años): "))
ec = input("Estado civil: ")
noh = int(input("¿Cuántos hijos tiene?:"))
estatura = input("Estatura (cm): ")
f_contrato = input("Fecha de ingreso al trabajo actual (dd/mm/aaaa): ")
salario = float(input("Sueldo básico (COP): "))
dias_lab = int(input("Cantidad de días laborados al mes:"))

if edad > 55:
  bonop = round(salario * 0.05, 0)
  print(f"\nCuenta con bono de prepensión igual a ${bonop}")
else:
  print(f"\nNo cumple con los requisitos para adquirir bono de prepensión")
if ec in "Casad" or "casad" and noh != 0:
  print("\nPaseo decembrino")
else:
  print("\nNo cumple con los requisitos para acceder al paseo decembrino")
if salario >= 1000000 and salario <= 1500000:
  com1 = round(salario * 0.02, 0)
  print(f"\nRecibirá comisión de ${com1}")
elif salario >= 1500001 and salario <= 2000000:
  com2 = round(salario *0.05, 0)
  print(f"\nRecibirá comisión de ${com2}")
else:
  print("\nNo cuenta con los requisistos para obtener comisión")
if dias_lab > 20 and salario < 1000000:
  print("\nDerecho a bono de alimentación")
else:
  print("\nNo aplica para el bono de alimentación")

"""**TALLER DE REFUERZO**

Diseña un programa en PYTHON para cada uno de los problemas
que se te plantean. 
1. Se necesita un sistema que despliega una tabla de
multiplicar de un número dado por el usuario. ciclo for 👌
2. Se necesita un sistema que pida un sueldo de un
trabajador, si el sueldo es mayor a 655000, no tedrá
ninguna bonificación, pero si es menor tiene bonificación
del 4%. Al final se desea saber el total del sueldo con
o sin bonificación. Preguntar si desea ejecutar de nuevo
el programa con el ciclo while. 👌
3. Un maestro necesita un sistema para capturar las
calificaciones de 5 parciales de sus alumnos, después
recapturarlas necesita que se despliegue el promedio,
cuando ya no quiera capturar más alumnos, necesita que
se despliegue el promedio general de todos los alumnos
capturados. Preguntar si desea ejecutar de nuevo el
programa con el ciclo while. 👌
4. Crear un bucle que cuente todos los números pares hasta
el 100 ciclo for 👌
5. Haz una tabla de multiplicar utilizando el ciclo for
ciclo for 👌
6. Escribir un programa que pregunte al usuario su edad y
muestre por pantalla todos los años que ha cumplido
(desde 1 hasta su edad). ciclo for 👌
"""

# Ejercicio 6
ed = int(input("¿Cuál es su edad?: "))

for i in range(1, ed + 1, 1):
  print(i, "años")

# Ejercicio 5
x = 17
for i in range(11):
  mult = x * i
  print( i, " x ", x, " = ", mult)

# Ejercicio 3
res = "si"
proma = 0
noe = 0

while res == "si" or res =="s" or res == "yes" or res == "sí":
  p1 = float(input("Digite la parcial 1: "))
  p2 = float(input("Digite la parcial 2: "))
  p3 = float(input("Digite la parcial 3: "))
  p4 = float(input("Digite la parcial 4: "))
  p5 = float(input("Digite la parcial 5: "))

  prom = round((p1 + p2 + p3 + p4 + p5)/5, 2)
  noe = noe + 1
  print(f"El promedio es: {prom}")
  proma = round(proma + prom, 2)
  res = input("¿Desea ingresar un nuevo registro?: ")
print(f"El promedio acumulado es = {proma/noe}")

# Ejercicio 4
for i in range(0,101,2):
  print(i)

# Ejercicio 1
num = int(input("De qué numero desea la tabla de multiplicar: "))

for i in range(11):
  print(i, " x ", num, " = ", i * num)

#Ejercicio 2
res = "Sí"
while res == "Sí" or res == "sí" or res == "si" or res == "Si" or res == "SI" or res == "SÍ" or res == "yes" or res == "YES":
  sal = int(input("\nDigite su sueldo: "))
  # no se específica si es mayor que o mayor igual, por lo que el límite queda sujeto a cada quien. 
  if sal <= 655000:
    bon = sal * 0.04
  else:
    bon = 0
  tot = sal + bon
  print(f"\nSu bonificación es de {bon}, para un total de {tot}")
  res = input("\n¿Desea calcular un nuevo sueldo total?: ")

"""**TALLER 3**"""

# INTERGAR TALLER 1 Y TALLER 2

def colaborador():
  no_ident = input("\nNo identificación: ")
  nom = input("Nombres: ")
  ap = input("Apellidos:")
  direc = input("Dirección de residencia: ")
  tel = input("Telefono de contacto: ")
  edad = int(input("Edad (años): "))
  ec = input("Estado civil: ")
  noh = int(input("¿Cuántos hijos tiene?:"))
  estatura = input("Estatura (cm): ")
  f_contrato = input("Fecha de ingreso al trabajo actual (dd/mm/aaaa): ")
  salario = float(input("Sueldo básico (COP): "))
  dias_lab = int(input("Cantidad de días laborados al mes:"))

  if edad > 55:
    bonop = round(salario * 0.05, 0)
    print(f"\nCuenta con bono de prepensión igual a ${bonop}")
  else:
    print(f"\nNo cumple con los requisitos para adquirir bono de prepensión")
  if ec == "casado" or ec == "casada" and noh != 0:
    print("\nPaseo decembrino")
  else:
    print("\nNo cumple con los requisitos para acceder al paseo decembrino")
  if salario >= 1000000 and salario <= 1500000:
    com1 = round(salario * 0.02, 0)
    print(f"\nRecibirá comisión de ${com1}")
  elif salario >= 1500001 and salario <= 2000000:
    com2 = round(salario *0.05, 0)
    print(f"\nRecibirá comisión de ${com2}")
  else:
    print("\nNo cuenta con los requisistos para obtener comisión")
  if dias_lab > 20 and salario < 1000000:
    print("\nDerecho a bono de alimentación")
  else:
    print("\nNo aplica para el bono de alimentación")

res = "si"
con = 0

while res == "si" or res == "si" or res == "sí" or res == "SI" or res == "Si":
  colaborador()
  con = con + 1
  print(f"\nHa ingresado {con} colaboradores..")
  res = input("\n¿Desea ingresar un nuevo colaborador?: ")